config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'youtube_users#create'
  get 'auth/failure', to: redirect('/')

  root 'home#index'

  resources :users do
    get '/dashboard', to: 'dashboard#show'

    resources :performances do
      resources :performance_pieces, only: [:new, :create]
    end

    resources :pieces do
      resources :youtube_uploads, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
        get 'youtube/comments', to: 'youtube#comments'
        delete 'youtube/delete', to: 'youtube#destroy'
        patch 'youtube/like', to: 'youtube#like'
        patch 'youtube/dislike', to: 'youtube#dislike'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:slug' => 'dashboard#show'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    if params[:slug]
      render :file => "public/404", :status => 404 if User.exists?(username: params[:slug]) == false
      @user = User.find_by(username: params[:slug]) if User.exists?(username: params[:slug])
    elsif params[:user_id]
      render :file => "public/404", :status => 404 if User.exists?(params[:user_id]) == false
      @user = User.find(params[:user_id]) if User.exists?(params[:user_id])
    end
  end

end

app/views/dashboard/show.html.erb
<div class="show">
  <h1 class="text-center" id="dashboard-header"> <%= @user.username %>'s Portfolio </h3>
  <div class="row-fluid" id="testytest1">
    <div class="col-sm-1"></div>
    <div class="col-sm-5">
      <div class="thumbnail" style="margin:0px auto; height:80%; width: 80%;">
        <img src="/replist.jpg" alt="replist">
        <div class="caption" style="text-align: center;">
          <h3>Repertoire</h3>
          <p>List of works performed</p>
          <p><%= button_to "Go", user_pieces_path(@user), method: :get, class:"btn btn-primary add-bottom" %></p>
        </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="thumbnail" style="margin:0px auto; height:80%; width: 80%;">
        <img src="/performances.jpg" alt="replist">
        <div class="caption" style="text-align: center;">
          <h3>Performances</h3>
          <p>List of performances</p>
          <p><%= button_to "Go", user_performances_path(@user), method: :get, class:"btn btn-primary" %></p>
        </div>
      </div>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>