config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'youtube_users#create'
  get 'auth/failure', to: redirect('/')

  root 'home#index'

  resources :users do
    get '/dashboard', to: 'dashboard#show'

    resources :performances do
      resources :performance_pieces, only: [:new, :create]
    end

    resources :pieces do
      resources :youtube_uploads, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
        get 'youtube/comments', to: 'youtube#comments'
        delete 'youtube/delete', to: 'youtube#destroy'
        patch 'youtube/like', to: 'youtube#like'
        patch 'youtube/dislike', to: 'youtube#dislike'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:slug' => 'dashboard#show'

end

app/models/piece.rb
require 'uri'

class Piece < ApplicationRecord
  has_many :performance_pieces
  has_many :performances, through: :performance_pieces

  belongs_to :user

  validates_presence_of :title

  before_save :get_uid

  validates_format_of :yt_link, :with => URI::regexp(%w(http https)), :allow_blank => true

  def get_uid
    if self.yt_link != ""
      query_string = URI.parse(self.yt_link).query
      parameters = Hash[URI.decode_www_form(query_string)]
      self.yt_uid = parameters['v']
    end
  end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :check_yt, :only => :show

  def index
    @user = User.find(params[:user_id])
    @yt_users = YoutubeUser.all
  end

  def show
    @presenter = Presenter.new(params[:user_id], params[:id], current_user)
  end

  def new
    @user = User.find(params[:user_id])
    @piece = Piece.new
  end

  def create
    @piece = current_user.pieces.new(piece_params)
    if @piece.save
      flash[:success] = "'#{@piece.title}' Successfully Added"
      redirect_to user_pieces_path(current_user)
    else
      flash[:danger] = "Invalid Attributes"
      redirect_to new_user_piece_path(current_user)
    end
  end

  def edit
    @piece = Piece.find(params[:id])
    @user = current_user
  end

  def update
    @user = current_user
    @piece = Piece.find(params[:id])
    if @piece.update(piece_params)
      flash[:success] = "Updated!"
      redirect_to user_pieces_path(@user)
    else
      flash[:danger] = "Invalid Attributes"
      redirect_to edit_user_piece_path(@user, @piece)
    end
  end

  def destroy
    @user = current_user
    @piece = Piece.find(params[:id])
    @piece.destroy
    flash[:success] = "Deleted!"
    redirect_to user_pieces_path(@user)
  end

  private

  def piece_params
    params.require(:piece).permit(:composer_last, :composer_first, :title, :yt_link)
  end

  def check_yt
    piece = Piece.find(params[:id])
    user = YoutubeUser.find_by(user_id: params["user_id"].to_i)
    if piece.yt_uid != "" && piece.yt_uid != nil && user != nil
      piece.update_attributes(yt_uid: "", yt_link: "") if YoutubeService.on_yt?(piece.yt_uid) == false
    end
  end

end

app/helpers/pieces_helper.rb
module PiecesHelper

  def authed_user_no_vid(presenter)
    presenter.piece.yt_link == "" && presenter.user == current_user && presenter.yt_users.exists?(user_id: current_user.id)
  end

  def authed_user_vid(presenter)
    presenter.piece.yt_link != "" && presenter.user == current_user && presenter.yt_users.exists?(user_id: current_user.id)
  end

  def nonauthed_user_vid(presenter)
    presenter.piece.yt_link == "" && presenter.user == current_user && !presenter.yt_users.exists?(user_id: current_user.id)
  end

  def authed_user_other_vid(presenter)
    presenter.piece.yt_link != "" && current_user && presenter.yt_users.exists?(user_id: current_user.id)
  end

  def nonauthed_user_other_vid(presenter)
    presenter.piece.yt_link != "" && current_user && !presenter.yt_users.exists?(user_id: current_user.id)
  end

end

app/views/pieces/edit.html.erb
<h2 class="text-center">New Piece</h2>

<div class="col-md-4"></div>
<div class="col-md-4" id: "shrink-me">

<%= bootstrap_form_for [@user, @piece] do |f| %>
  <%= f.text_field :composer_last, placeholder: "Composer's Last" %>

  <%= f.text_field :composer_first, placeholder: "Composer's First" %>

  <%= f.text_field :title, placeholder: "Title of Piece" %>

  <%= f.text_field :yt_link, placeholder: "YouTube URL" %>

  <div class="center-me">
    <%= f.submit "Edit Piece", class: "update-btn" %>
  </div>

  <% end %>

  </div>
  <div class="col-md-4"></div>

app/views/pieces/index.html.erb
<div class="text-center">
  <h1>Repertoire List</h1>
</div>

<div class="col-md-8 col-md-push-2">

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Last</th>
      <th>First</th>
      <th>Title</th>
      <th> </th>
      <% if current_user == @user %>
      <th></th>
      <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user.pieces.each do |piece| %>
    <tr>
      <td><%= piece.composer_last %></td>
      <td><%= piece.composer_first %></td>
      <td><%= piece.title %></td>
      <td>
        <%= link_to user_piece_path(@user, piece) do %>
        <button type="button" style="font-size:.5em;" class="btn btn-primary">View</button>
        <% end %>
      </td>
      <% if current_user == @user %>
      <td>
      <%= link_to edit_user_piece_path(@user, piece) do %>
        <i style="font-size:1.5em;" class="glyphicon glyphicon-cog"></i>
      <% end %>
      </td>
      <td class="delete-<%=piece.title%>">
        <%= link_to user_piece_path(@user, piece), method: :delete do %>
        <i style="font-size:1.5em;" class="glyphicon glyphicon-remove-sign"></i>
        <% end %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
  <div class="new-piece-button">
    <% if current_user == @user %>
    <%= button_to 'New Piece', new_user_piece_path(@user), method: :get, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/pieces/new.html.erb
<h2 class="text-center">New Piece</h2>

<div class="col-md-4"></div>
<div class="col-md-4" id: "shrink-me">

<%= bootstrap_form_for [@user, @piece] do |f| %>
  <%= f.text_field :composer_last, placeholder: "e.g. Ibert" %>

  <%= f.text_field :composer_first, placeholder: "e.g. Jacques" %>

  <%= f.text_field :title, placeholder: "e.g. Concertino da Camera" %>

  <%= f.text_field :yt_link, label: "Link (if video already exists on YouTube)", placeholder: "e.g. https://www.youtube.com/watch?v=H7iJIp_C32A" %>

  <div class="center-me">
    <%= f.submit "Add Piece", class: "update-btn" %>
  </div>

  <% end %>

  </div>
  <div class="col-md-4"></div>

app/views/pieces/show.html.erb
<div class="container-fluid pieces-show">
  <div class="row">
    <div class="col-md-3"></div>
     <div class="col-md-6 center-center">
      <% if @presenter.piece.yt_link != "" %>
        <div class="youtube-player" data-id="<%=@presenter.piece.yt_uid%>"></div>
        <div class="youtube-icons">
          <button id="yt-comments" class="btn btn-default"
                                   data-ytid="<%=@presenter.piece.yt_uid%>"
                                   data-status="hiding">
                                   <i class="glyphicon glyphicon-comment"></i>
          </button>
        <% end %>
        <!-- if video exists, user is visiting their own page, and they're oauthed -->
        <% if authed_user_vid(@presenter) %>
          <button id="yt-del" class="btn btn-default"
                              data-ytid="<%=@presenter.piece.yt_uid%>"
                              data-pieceid="<%=@presenter.piece.id%>">
                              <i class="glyphicon glyphicon-trash"></i>
          </button>
        <% end %>
        <!-- if there is a video present, user is logged in, and they ARE oauthed -->
        <% if authed_user_other_vid(@presenter) %>
          <button id="yt-like" class="btn btn-default"
                               data-ytid="<%=@presenter.piece.yt_uid%>">
                               <i class="glyphicon glyphicon-thumbs-up"></i>
          </button>
          <button id="yt-dislike" class="btn btn-default"
                               data-ytid="<%=@presenter.piece.yt_uid%>">
                               <i class="glyphicon glyphicon-thumbs-down"></i>
          </button>
        <% end %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @presenter.piece.title %></h3>
        </div>
        <div class="panel-body">
          <%= @presenter.piece.composer_first %> <%= @presenter.piece.composer_last %>
        </div>
      </div>
      <div class="row testytesty">
        <!-- piece has no video added to it, user is on their own page, and they're NOT oauthed -->
        <% if nonauthed_user_vid(@presenter) %>
          <p style="color:#f92d27"> *Authorize your account with YouTube to upload a video </p>
        <% end %>
        <!-- if there is a video present, user is logged in, and they're NOT oauthed -->
        <% if nonauthed_user_other_vid(@presenter) %>
          <p style="color:#f92d27"> *Authorize your account with YouTube to like or dislike video </p>
        <% end %>
        <!-- piece has no video added to it, user is on their own page, and they're oauthed -->
        <% if authed_user_no_vid(@presenter) %>
          <%= button_to 'Upload Video', new_user_piece_youtube_upload_path(current_user.id, @presenter.piece.id), form_class: "testytesty", method: :get, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <div class="col-md-3"></div>
</div>
<div class="col-md-6 col-md-offset-3 comments"></div>
</div>