config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'youtube_users#create'
  get 'auth/failure', to: redirect('/')

  root 'home#index'

  resources :users do
    get '/dashboard', to: 'dashboard#show'

    resources :performances do
      resources :performance_pieces, only: [:new, :create]
    end

    resources :pieces do
      resources :youtube_uploads, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
        get 'youtube/comments', to: 'youtube#comments'
        delete 'youtube/delete', to: 'youtube#destroy'
        patch 'youtube/like', to: 'youtube#like'
        patch 'youtube/dislike', to: 'youtube#dislike'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:slug' => 'dashboard#show'

end

app/models/performance.rb
class Performance < ApplicationRecord
  has_many :performance_pieces
  has_many :pieces, through: :performance_pieces

  belongs_to :user
  validates_presence_of :title
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @performances = @user.performances.all
  end

  def show
    @user = User.find(params[:user_id])
    @performance = Performance.find(params[:id])
    @pieces = @performance.pieces
  end

  def new
    @user = current_user
    @performance = Performance.new
  end

  def create
    @performance = Performance.new(performance_params)
    if @performance.save
      flash[:success] = "Performance Added!"
    else
      flash[:warning] = "Oops! There was a problem"
    end
    redirect_to user_performances_path(current_user)
  end

  private

  def performance_params
    params.require(:performance).permit(:title, :date).merge(user_id: current_user.id)
  end
end

app/views/performances/index.html.erb
<h3 class="text-center" id="dashboard-header"> <%= @user.username %>'s Performances </h3>

<div class="col-md-6 col-md-push-3">

<% @user.performances.each do |perf| %>
<div class="well well-lg">
  <p> <%= link_to perf.title, user_performance_path(@user, perf) %> </p>
  <p> <%= perf.date %> </p>
</div>
<% end %>

<div class="right-me">
  <%= button_to "Add Performance", new_user_performance_path, :class => "btn btn-success btn-sm", :method => :get %>
</div>

</div>

app/views/performances/new.html.erb
<h2 class="text-center">New Performance</h2>

<div class="col-md-4"></div>

<div class="col-md-4">
  <%= form_for [@user, @performance] do |f| %>

    <div class="form-group row">
      <label class="col-2 col-form-label">Title</label>
      <div class="col-10">
        <%= f.text_field :title, placeholder: "e.g. Senior Recital", class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-2 col-form-label">Date</label>
      <div class="col-10">
        <%= f.text_field :date, class: "form-control", type: "date", value: "#{Date.today.to_s}" %>
      </div>
    </div>

    <div class="center-me">
      <%= f.submit "Add Performance", class: "update-btn" %>
    </div>

  <% end %>
</div>

<div class="col-md-4"></div>

app/views/performances/show.html.erb
<h3 class=text-center> <%= @performance.title %> </h3>

<div class="col-md-4 col-md-push-4">
  <% @performance.pieces.each do |piece| %>
    <div class="well well-lg">
      <p> <%= link_to piece.title, user_piece_path(current_user, piece) %> </p>
      <p> <%= piece.composer_last %> </p>
      <p> <%= piece.composer_first %> </p>
    </div>
  <% end %>
  <div class="col-md-4 col-md-push-4">
    <% if @user == current_user %>
    <%= button_to "Add Piece",
    new_user_performance_performance_piece_path(current_user, @performance),
    :class => "btn btn-success btn-sm", :method => :get %>
    <% end %>
  </div>
</div>