config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'youtube_users#create'
  get 'auth/failure', to: redirect('/')

  root 'home#index'

  resources :users do
    get '/dashboard', to: 'dashboard#show'

    resources :performances do
      resources :performance_pieces, only: [:new, :create]
    end

    resources :pieces do
      resources :youtube_uploads, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
        get 'youtube/comments', to: 'youtube#comments'
        delete 'youtube/delete', to: 'youtube#destroy'
        patch 'youtube/like', to: 'youtube#like'
        patch 'youtube/dislike', to: 'youtube#dislike'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:slug' => 'dashboard#show'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <div class="navbar-form navbar-left">
        <%= form_tag(users_path, method: 'get') do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <% if !YoutubeUser.exists?(user_id: current_user.id) %>
          <li><%= link_to 'YouTube Sync', '/auth/google_oauth2' %></li>
        <% end %>
          <li><%= link_to "Portfolio", user_dashboard_path(current_user) %></li>
          <li class="logout"><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Create Account", new_user_path %></li>
          <li class="login"><%= link_to "Log In", login_path %></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Replist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>